### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by benoitStein** [daften/addressing-bundle#19]
WIP

**Comment by daften** [comment]
At the moment I am using the bundle on Symfony 5 LTS without issues, do you have any problems with Symfony 5 @benoitStein ?

**Comment by Sylry** [comment]
I think this is more an issue with commerceguys/addressing: fields property has been deprecated in favor of fieldOverrides:
https://github.com/OWS/addressing-bundle/tree/sf5_compatibility

Do you want me to open a PR with a new named branch or this one is ok for you?

PS: we are working together with Benoit, and sorry for the delay of the response

**Comment by daften** [comment]
Hi @Sylry 

There is no MR open, so yes, opening one would be very helpful.

Thanks and no problem, it sometimes takes a while for me to get around to it too :) Thanks for contributing!

**Comment by daften** [comment]
Closing this since the MR is merged. Thanks for the contribution!
